class NutritionValue {
  final String menuName;
  final double kalori;
  final double protein;
  final double karbohidrat;
  final double lemak;
  final double serat;
  final double vitaminA;
  final double vitaminC;
  final double kalsium;
  final double zatBesi;

  NutritionValue({
    required this.menuName,
    required this.kalori,
    required this.protein,
    required this.karbohidrat,
    required this.lemak,
    this.serat = 0,
    this.vitaminA = 0,
    this.vitaminC = 0,
    this.kalsium = 0,
    this.zatBesi = 0,
  });
}

// Data dummy 20 menu
final List<NutritionValue> dummyMenus = [
  NutritionValue(
    menuName: 'Nasi Goreng Spesial',
    kalori: 450,
    protein: 12,
    karbohidrat: 65,
    lemak: 15,
    serat: 3,
    vitaminA: 120,
    vitaminC: 8,
    kalsium: 50,
    zatBesi: 2.5,
  ),
  NutritionValue(
    menuName: 'Ayam Bakar Taliwang',
    kalori: 380,
    protein: 28,
    karbohidrat: 10,
    lemak: 18,
    serat: 2,
    vitaminA: 80,
    vitaminC: 5,
    kalsium: 40,
    zatBesi: 3.0,
  ),
  NutritionValue(
    menuName: 'Sayur Asem',
    kalori: 120,
    protein: 4,
    karbohidrat: 18,
    lemak: 3,
    serat: 5,
    vitaminA: 200,
    vitaminC: 15,
    kalsium: 80,
    zatBesi: 1.5,
  ),
  NutritionValue(
    menuName: 'Ikan Bakar Rica',
    kalori: 320,
    protein: 32,
    karbohidrat: 5,
    lemak: 12,
    serat: 1,
    vitaminA: 60,
    vitaminC: 10,
    kalsium: 60,
    zatBesi: 2.0,
  ),
  NutritionValue(
    menuName: 'Tumis Kangkung',
    kalori: 95,
    protein: 3,
    karbohidrat: 8,
    lemak: 5,
    serat: 4,
    vitaminA: 300,
    vitaminC: 25,
    kalsium: 100,
    zatBesi: 2.0,
  ),
  NutritionValue(
    menuName: 'Soto Ayam',
    kalori: 280,
    protein: 18,
    karbohidrat: 30,
    lemak: 8,
    serat: 2,
    vitaminA: 150,
    vitaminC: 12,
    kalsium: 70,
    zatBesi: 1.8,
  ),
  NutritionValue(
    menuName: 'Gado-gado',
    kalori: 350,
    protein: 10,
    karbohidrat: 40,
    lemak: 14,
    serat: 6,
    vitaminA: 250,
    vitaminC: 20,
    kalsium: 120,
    zatBesi: 2.5,
  ),
  NutritionValue(
    menuName: 'Rawon',
    kalori: 420,
    protein: 22,
    karbohidrat: 45,
    lemak: 16,
    serat: 3,
    vitaminA: 100,
    vitaminC: 8,
    kalsium: 55,
    zatBesi: 3.5,
  ),
  NutritionValue(
    menuName: 'Pepes Tahu',
    kalori: 180,
    protein: 12,
    karbohidrat: 15,
    lemak: 8,
    serat: 4,
    vitaminA: 70,
    vitaminC: 6,
    kalsium: 90,
    zatBesi: 2.0,
  ),
  NutritionValue(
    menuName: 'Opor Ayam',
    kalori: 400,
    protein: 25,
    karbohidrat: 20,
    lemak: 22,
    serat: 2,
    vitaminA: 130,
    vitaminC: 4,
    kalsium: 45,
    zatBesi: 2.2,
  ),
  NutritionValue(
    menuName: 'Cap Cay',
    kalori: 150,
    protein: 6,
    karbohidrat: 20,
    lemak: 5,
    serat: 5,
    vitaminA: 280,
    vitaminC: 35,
    kalsium: 85,
    zatBesi: 1.5,
  ),
  NutritionValue(
    menuName: 'Rendang',
    kalori: 520,
    protein: 35,
    karbohidrat: 15,
    lemak: 30,
    serat: 2,
    vitaminA: 90,
    vitaminC: 3,
    kalsium: 50,
    zatBesi: 4.0,
  ),
  NutritionValue(
    menuName: 'Pempek',
    kalori: 300,
    protein: 8,
    karbohidrat: 45,
    lemak: 10,
    serat: 1,
    vitaminA: 20,
    vitaminC: 2,
    kalsium: 30,
    zatBesi: 1.0,
  ),
  NutritionValue(
    menuName: 'Sate Padang',
    kalori: 450,
    protein: 28,
    karbohidrat: 35,
    lemak: 20,
    serat: 2,
    vitaminA: 110,
    vitaminC: 6,
    kalsium: 65,
    zatBesi: 3.2,
  ),
  NutritionValue(
    menuName: 'Lontong Sayur',
    kalori: 350,
    protein: 8,
    karbohidrat: 50,
    lemak: 12,
    serat: 4,
    vitaminA: 180,
    vitaminC: 10,
    kalsium: 95,
    zatBesi: 2.0,
  ),
  NutritionValue(
    menuName: 'Mie Ayam',
    kalori: 420,
    protein: 16,
    karbohidrat: 60,
    lemak: 14,
    serat: 2,
    vitaminA: 80,
    vitaminC: 5,
    kalsium: 40,
    zatBesi: 2.2,
  ),
  NutritionValue(
    menuName: 'Bubur Ayam',
    kalori: 280,
    protein: 12,
    karbohidrat: 45,
    lemak: 6,
    serat: 1,
    vitaminA: 100,
    vitaminC: 3,
    kalsium: 35,
    zatBesi: 1.5,
  ),
  NutritionValue(
    menuName: 'Nasi Uduk',
    kalori: 380,
    protein: 10,
    karbohidrat: 55,
    lemak: 12,
    serat: 1,
    vitaminA: 40,
    vitaminC: 2,
    kalsium: 25,
    zatBesi: 1.2,
  ),
  NutritionValue(
    menuName: 'Kerak Telor',
    kalori: 320,
    protein: 14,
    karbohidrat: 35,
    lemak: 18,
    serat: 1,
    vitaminA: 150,
    vitaminC: 5,
    kalsium: 70,
    zatBesi: 2.0,
  ),
  NutritionValue(
    menuName: 'Es Buah',
    kalori: 180,
    protein: 2,
    karbohidrat: 40,
    lemak: 1,
    serat: 5,
    vitaminA: 220,
    vitaminC: 45,
    kalsium: 30,
    zatBesi: 0.5,
  ),
];